version: '3.1'



services:

  rssbot:

    image: fengkx/node_rssbot

    container_name: node_rssbot

    restart: always

    volumes:

      - /var/data:/app/data/

    ports:

      - 3333:3333

    environment:

      RSSBOT_TOKEN: 5880712260:AAEVReyV5aihHIZZDQj8tH4w4IEbApEOYpA

    networks:

      - my-bridge



networks:

  my-bridge:

    driver: bridge
